env:
  - RUNTESTS=True
  - PUBLISHMETA=True
  - PUBLISHDOCS=True
  - TARGET=CC3D
  - TARGET=CC3D OPBL=yes
  - TARGET=CHEBUZZF3
  - TARGET=CJMCU
  - TARGET=EUSTM32F103RC
  - TARGET=SPRACINGF3
  - TARGET=NAZE
  - TARGET=NAZE32PRO
  - TARGET=OLIMEXINO
  - TARGET=PORT103R
  - TARGET=SPARKY
  - TARGET=STM32F3DISCOVERY
  - TARGET=ALIENWIIF1
  - TARGET=ALIENWIIF3

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install:
  - sudo apt-get update
  - wget "https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q3-update/+download/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2"

install: 
  - sudo apt-get install build-essential git libc6-i386
  - tar -xf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_8-2014q3/bin
   
before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

cache: apt

notifications:
  irc: "chat.freenode.net#cleanflight"
  use_notice: true
  skip_join: true